<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

<!--
  Author: Kelsey Hawkins
  Contributers: Jimmy Da Silva, Ajit Krisshna N L, Muhammad Asif Rana
-->
  <xacro:include filename="./common_materials.xacro"/>
  <xacro:include filename="./ur.transmission.xacro" />
  <xacro:include filename="./ur.gazebo.xacro" />


  <xacro:macro name="_inertial" >
    <!-- <inertial> -->
    <inertia ixx="1.0e-05" ixy="0.0" ixz="0.0"
      iyy="1.0e-05" iyz="0.0"
      izz="1.0e-05" />
    <!-- </inertial> -->
  </xacro:macro>

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="aubo_robot" params="prefix joint_limited
    shoulder_pan_lower_limit:=${-pi}    shoulder_pan_upper_limit:=${pi}
    shoulder_lift_lower_limit:=${-pi}    shoulder_lift_upper_limit:=${pi}
    elbow_joint_lower_limit:=${-pi}    elbow_joint_upper_limit:=${pi}
    wrist_1_lower_limit:=${-pi}    wrist_1_upper_limit:=${pi}
    wrist_2_lower_limit:=${-pi}    wrist_2_upper_limit:=${pi}
    wrist_3_lower_limit:=${-pi}    wrist_3_upper_limit:=${pi}
    transmission_hw_interface:=PositionJointInterface
    safety_limits:=false safety_pos_margin:=0.15
    safety_k_position:=20">

    <!-- Inertia parameters -->
    <xacro:property name="base_mass" value="1.2345" />  <!-- This mass might be incorrect -->
    <xacro:property name="shoulder_mass" value="10.994" />
    <xacro:property name="upper_arm_mass" value="5.3139" />
    <xacro:property name="forearm_mass" value="3.1022" />
    <xacro:property name="wrist_1_mass" value="1.96" />
    <xacro:property name="wrist_2_mass" value="1.96" />
    <xacro:property name="wrist_3_mass" value="0.202" />

    <!-- These parameters are borrowed from the urcontrol.conf file
        but are not verified for the correct permutation.
        The permutation was guessed by looking at the UR5 parameters.
        Serious use of these parameters needs further inspection. -->
    <xacro:property name="shoulder_cog" value="0.00008 0.00244 -0.037" />
    <xacro:property name="upper_arm_cog" value="0.00001 0.15061 0.38757" />
    <xacro:property name="forearm_cog" value="-0.00012 0.06112 0.1984" />
    <xacro:property name="wrist_1_cog" value="-0.00021 -0.00112 0.02269" />
    <xacro:property name="wrist_2_cog" value="-0.00021 0.00112 0.002269" />
    <xacro:property name="wrist_3_cog" value="0 -0.001156 -0.00149" />

    <!-- Kinematic model -->
    <!-- Properties from urcontrol.conf -->
    <xacro:property name="d1" value="0.1273" />
    <xacro:property name="a2" value="-0.612" />
    <xacro:property name="a3" value="-0.5723" />
    <xacro:property name="d4" value="0.163941" />
    <xacro:property name="d5" value="0.1157" />
    <xacro:property name="d6" value="0.0922" />

    <!-- Arbitrary offsets for shoulder/elbow joints -->
    <xacro:property name="shoulder_offset" value="0.220941" />  <!-- measured from model -->
    <xacro:property name="elbow_offset" value="-0.1719" /> <!-- measured from model -->
    <xacro:property name="upper_arm_inertia_offset" value="0.045" />  <!-- measured from model -->

    <!-- link lengths used in model -->
    <xacro:property name="shoulder_height" value="${d1}" />
    <xacro:property name="upper_arm_length" value="${-a2}" />
    <xacro:property name="forearm_length" value="${-a3}" />
    <xacro:property name="wrist_1_length" value="${d4 - elbow_offset - shoulder_offset}" />
    <xacro:property name="wrist_2_length" value="${d5}" />
    <xacro:property name="wrist_3_length" value="${d6}" />

    <link name="${prefix}base_link" >
      <inertial>
        <origin rpy="0 0 0" xyz="-2.7535E-06 0.00054789 -0.02299"/>
        <mass value="1.2345"/>
        <inertia ixx="0.0029215E-02" ixy="2.2046E-07" ixz="-3.4773E-08" iyy="0.0028546E-02" iyz="-7.6362E-06" izz="0.0051176"/>
        <!-- <xacro:_inertial /> -->
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/base_link.DAE"/>
        </geometry>
        <material name="">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/base_link.STL"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}shoulder_pan_joint" type="revolute">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}shoulder_link" />
      <origin rpy="-8.7138E-17 -4.3534E-32 3.1416" xyz="0 0 0.1632"/>
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_pan_lower_limit}" upper="${shoulder_pan_upper_limit}" effort="330.0" velocity="2.16"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${shoulder_pan_lower_limit + safety_pos_margin}" soft_upper_limit="${shoulder_pan_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <!-- <dynamics damping="0.0" friction="0.0"/> -->
    </joint>

    <link name="${prefix}shoulder_link">
      <inertial>
        <origin rpy="0 0 0" xyz="0.00029287 0.14173 0.54281"/>
        <mass value="10.994e-01"/>
        <!-- <xacro:_inertial /> -->
        <inertia ixx="2.2088e-02" ixy="-0.00043922e-02" ixz="-0.0025417e-02" iyy="2.1473e-02" iyz="-0.049088e-02" izz="0.07998e-02"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/shoulder_Link.DAE"/>
        </geometry>
        <material name="">
          <color rgba="0.89804 0.91765 0.92941 1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/shoulder_Link.STL"/>
        </geometry>
      </collision>
    </link>
    
    <joint name="${prefix}shoulder_lift_joint" type="revolute">
      <parent link="${prefix}shoulder_link" />
      <child link = "${prefix}upper_arm_link" />
      <origin rpy="-1.5708 -1.5708 0" xyz="0 0.2013 0"/>
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_lift_lower_limit}" upper="${shoulder_lift_upper_limit}" effort="330.0" velocity="2.16"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${shoulder_lift_lower_limit + safety_pos_margin}" soft_upper_limit="${shoulder_lift_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}upper_arm_link">
      <inertial>
        <origin rpy="0 0 0" xyz="0.31908 -3.7071E-06 -0.0042956"/>
        <mass value="5.3139e-01"/>
        <!-- <xacro:_inertial /> -->
        <inertia ixx="0.0095171e-02" ixy="7.2849E-06" ixz="-6.7014E-06" iyy="0.11411e-02" iyz="-1.1529E-06" izz="0.11411e-02"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/upperArm_Link.DAE"/>
        </geometry>
        <material name="">
          <color rgba="0.89804 0.91765 0.92941 1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/upperArm_Link.STL"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}elbow_joint" type="revolute">
      <parent link="${prefix}upper_arm_link" />
      <child link = "${prefix}forearm_link" />
      <origin rpy="3.1416 -4.5954E-17 -8.4328E-17" xyz="0.647 0 0"/>
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${elbow_joint_lower_limit}" upper="${elbow_joint_upper_limit}" effort="150.0" velocity="3.15"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${elbow_joint_lower_limit + safety_pos_margin}" soft_upper_limit="${elbow_joint_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}forearm_link">
      <inertial>
        <origin rpy="0 0 0" xyz="0.24431 6.6794E-06 0.12549"/>
        <mass value="3.1022e-01"/>
        <!-- <xacro:_inertial /> -->
        <inertia ixx="0.0027288e-02" ixy="-6.2713E-06" ixz="-0.0018082e-02" iyy="0.097825e-02" iyz="3.5731E-07" izz="0.097866"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/foreArm_Link.DAE"/>
        </geometry>
        <material name="">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/foreArm_Link.STL"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}wrist_1_joint" type="revolute">
      <parent link="${prefix}forearm_link" />
      <child link = "${prefix}wrist_1_link" />
      <origin rpy="-3.1416 -1.4294E-15 1.5708" xyz="0.6005 0 0"/>
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_1_lower_limit}" upper="${wrist_1_upper_limit}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_1_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_1_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_1_link">
      <inertial>
        <origin rpy="0 0 0" xyz="5.2305E-07 0.00026581 -0.0027894"/>
        <mass value="0.0057981"/>
        <!-- <xacro:_inertial /> -->
        <inertia ixx="6.0946E-09" ixy="9.3663E-12" ixz="-1.3841E-12" iyy="5.9501E-09" iyz="1.9944E-09" izz="9.6981E-09"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/wrist1_Link.DAE"/>
        </geometry>
        <material name="">
          <color rgba="0.1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/wrist1_Link.STL"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}wrist_2_joint" type="revolute">
      <parent link="${prefix}wrist_1_link" />
      <child link = "${prefix}wrist_2_link" />
      <origin rpy="-1.5708 -7.0777E-16 -7.4101E-16" xyz="0 0.1025 0"/>
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_2_lower_limit}" upper="${wrist_2_upper_limit}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_2_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_2_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_2_link">
      <inertial>
        <origin rpy="0 0 0" xyz="-5.2305E-07 -0.00026581 -0.0027894"/>
        <mass value="0.00057981"/>
        <!-- <xacro:_inertial /> -->
        <inertia ixx="6.0946E-09" ixy="9.3663E-12" ixz="-1.3841E-12" iyy="5.9501E-09" iyz="1.9944E-09" izz="9.6981E-09"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/wrist2_Link.DAE"/>
        </geometry>
        <material name="">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/wrist2_Link.STL"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}wrist_3_joint" type="revolute">
      <parent link="${prefix}wrist_2_link" />
      <child link = "${prefix}wrist_3_link" />
      <origin rpy="1.5708 0 6.7283E-16" xyz="0 -0.094 0"/>
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_3_lower_limit}" upper="${wrist_3_upper_limit}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_3_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_3_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_3_link">
      <inertial>
        <origin rpy="0 0 0" xyz="-2.2127E-09 0.00023722 -0.018629"/>
        <mass value="0.000013669"/>
        <!-- <xacro:_inertial /> -->
        <inertia ixx="6.0946E-09" ixy="9.3663E-12" ixz="-1.3841E-12" iyy="5.9501E-09" iyz="1.9944E-09" izz="9.6981E-09"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/wrist3_Link.DAE"/>
        </geometry>
        <material name="">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="./meshes/aubo_i10/wrist3_Link.STL"/>
        </geometry>
      </collision>
    </link>

    

    <xacro:ur_arm_transmission prefix="${prefix}" hw_interface="${transmission_hw_interface}" />
    <xacro:ur_arm_gazebo prefix="${prefix}" />

    <link name="${prefix}tool_Link">
      <inertial>
        <origin rpy="0 0 0" xyz="-2.2127E-09 0.00023722 -0.018629"/>
        <mass value="1.36694e-06"/>
        <!-- <xacro:_inertial /> -->
        <inertia ixx="6.0946E-09" ixy="9.3663E-12" ixz="-1.3841E-12" iyy="5.9501E-09" iyz="1.9944E-09" izz="9.6981E-09"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh
            filename="./meshes/aubo_i10/Tool2.STL" />
        </geometry>
        <!-- <material name="material_fanuc_gray40"/> -->
          <!-- <color rgba="1 1 1 1"/>
        </material> -->
      </visual>
    </link>

 <!--/////////////////////////////// tool_JOINIT ////////////////////////////////////-->

    <joint name="${prefix}tool_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 3.1415926" />
        <parent link="${prefix}wrist_3_link" />
        <child link = "${prefix}tool_Link" />
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </joint>
  </xacro:macro>
</robot>
